# Generated by Django 2.2.11 on 2020-07-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=64)),
                ('starting_bid', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
